### ISSUE TITLE
question about data folder permissions

### ISSUE THREAD

**Issue by acme64** [Luctia/ezarr#11]
I'm in the process of modifying the instructions to install on a Synology NAS and I'm confused about line 28 in setup.sh
`sudo chown -R $(id -u):mediacenter data/`
Which user should be the owner here? Is it the regular Synology user? do they have to be a member of mediacenter?

same question for line 38
`echo "UID=$(id -u)" >> .env`

**Comment by Luctia** [comment]
Hi! I have no experience regarding Synology, but I reckon it is the regular user. The idea is that the "main" user (the one that is the first user with a /home directory in Linux) is the owner to these files, so that's probably the regular user.

Honestly, I doubt it would make a difference with the way permissions are set though. I'd make the regular user member of the mediacenter group and not think much more of it - this should be enough.

If this answer is enough, please close the issue, otherwise, don't doubt asking further questions :)

**Comment by acme64** [comment]
looks like its working! thank you for the quick reply!
