### ISSUE TITLE
Sonarr can't find root folder

### ISSUE THREAD

**Issue by cristiandiiorio** [Luctia/ezarr#19]
I've followed the readme guide but I have encountered problems when it says :

> Root folder: /data/media/ and then tv, movies or music depending on service

My sonarr can't find any folders inside /data/media so it doesn't let me use that as a root folder.
(My issue is similar to #14)

**Comment by mccxiv** [comment]
Having the same issue, Ubuntu 22.04 fresh install, used the CLI install 

![ds45gt](https://user-images.githubusercontent.com/1700359/212501259-59f5ad3b-b053-48b5-9bd1-785fa25a7a34.gif)

**Comment by cristiandiiorio** [comment]
> What did you do to set up your environment? Did you use the CLI or the manual method?

I had tried the manual install. Now I've tried the CLI install but I've encountered the same bug. 
Sorry if my answer is late.

**Comment by Luctia** [comment]
@cristiandiiorio can you verify that you ran the manual `.sh` script as superuser?

**Comment by cristiandiiorio** [comment]
> @cristiandiiorio can you verify that you ran the manual `.sh` script as superuser?

Yes

**Comment by Luctia** [comment]
I've found the cause, I think.

The `os.system` function in Python uses shell instead of bash, which doesn't understand the `{media,torrents}` structure that bash understands. On top of that, using `&&` makes it so the second part of the command will not be executed if the first part of the command errors out, which means the CLI doesn't work if you tried the manual version first (as `useradd` will exit with an error (code 9) if the user already exists). Working on a PR to fix that now.

**Comment by Luctia** [comment]
@cristiandiiorio and @mccxiv, can you try with the new version?

**Comment by Luctia** [comment]
Assuming this is fixed for now.
