### ISSUE TITLE
issue with bazarr path mapping

### ISSUE THREAD

**Issue by joihn** [Luctia/ezarr#68]
https://github.com/Luctia/ezarr/blob/main/docker-compose.yml.sample#L102C33-L102C38
```
- ${ROOT_DIR}/data/media:/media
```

I would advice instead
```
- ${ROOT_DIR}/data/media:/data/media
```
Such that sonarr and bazarr path mapping are the same , otherwise bazarr will not find the files

**Comment by Luctia** [comment]
Can you elaborate a bit more on why this is the case? Because it seems to work fine for me locally, and that makes sense to me. The path on the right of the colon is only visible within Bazarr, as long as you configure correctly that should work just fine, no? The path left of the colon should definitely be the same, but the path on the right can be whatever you want.

**Comment by Luctia** [comment]
You can see this in the Plex section too, by the way. That configuration also uses `/media` for the internal path.

**Comment by Luctia** [comment]
I'm gonna go ahead and close this issue for now. Changing this can be breaking for existing users and I'm not convinced there's anything broken about the current configuration.
